// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iydovtlbadzauyddfpov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZG92dGxiYWR6YXV5ZGRmcG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjIyNzEsImV4cCI6MjA2NTgzODI3MX0.GFAYj98O8skJKmkoBTN8bE7h03yks48qPnYTBuPXTFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);